drops/urls.py
from django.urls import path

from .views import (
    drop_search_view,
    drop_create_view,
    drop_detail_view,
    drop_list_view,
    drop_update_view,
    drop_delete_view,
    drop_detail_hx_view,
    drop_single_view
)

app_name = 'drops'
urlpatterns = [
    path('', drop_list_view, name='list'),
    #path('', drop_search_view, name='search'),
    path('create/', drop_create_view, name='create'),

    path("hx/<int:id>/", drop_detail_hx_view, name='hx-detail'),

    path("<int:id>/delete/", drop_delete_view, name='delete'),
    path("<int:id>/edit/", drop_update_view, name='update'),
    path("<int:id>/", drop_detail_view, name='detail'),

    path('<slug:slug>/', drop_single_view, name='single'),
]

rargorand/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from drops.views import schedule_view
from nftcollections.views import all_collections_view
from search.views import search_view
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('schedule/', schedule_view, name='schedule'),
    path('allcollections/', all_collections_view, name='collections'),
    path('library/nftcollections/', include('nftcollections.urls')),
    path('library/collections/', include('ncollections.urls')),
    path('calendar/drops/', include('drops.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

drops/models.py
import pathlib
import uuid

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from .utils import slugify_instance_title

User = settings.AUTH_USER_MODEL

class DropQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = Q(title__icontains=query) | Q(description__icontains=query)
        return self.filter(lookups)

class DropManager(models.Manager):
    def get_queryset(self):
        return DropQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)

def collection_image_upload_handler(instance, filename):
    fpath = pathlib.Path(filename)
    new_fname = str(uuid.uuid1()) # uuid1 -> uuid + timestamps
    return f"drops/{new_fname}{fpath.suffix}"

class Drop(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120, blank=False, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    description = models.TextField(max_length=500, blank=False, null=True)
    genre = models.CharField(max_length=120, default=None, blank=True, null=True)
    featured = models.BooleanField(default=False)
    mostanticipated = models.BooleanField(default=False)
    futurefavourite = models.BooleanField(default=False)
    release_date = models.CharField(max_length=250, blank=False, null=True)
    release_time = models.TimeField(auto_now=False, auto_now_add=False, default=None, blank=False, null=True)
    timestamp = models.DateField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=collection_image_upload_handler, blank=True, null=True)

    objects = DropManager()

    @property
    def name(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("drops:detail", kwargs={"id": self.id})

    def get_single_drop_url(self):
        return reverse("drops:single", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) 

    def get_hx_url(self):
        return reverse("drops:hx-detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("drops:update", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("drops:delete", kwargs={"id": self.id})  

def drop_pre_save(sender, instance, *args, **kwargs):
    if instance.slug is None:
        slugify_instance_title(instance, save=False)

pre_save.connect(drop_pre_save, sender=Drop)

def drop_post_save(sender, instance, created, *args, **kwargs):
    if created:
        slugify_instance_title(instance, save=True)
        instance.save()

post_save.connect(drop_post_save, sender=Drop)

drops/forms.py
from django import forms

from .models import Drop

class DropForm(forms.ModelForm):
    class Meta:
        model = Drop
        fields = ['title', 'release_date', 'release_time', 'description', 'image', 'genre']
        

    def clean(self):
        data = self.cleaned_data
        title = data.get("title")
        qs = Drop.objects.filter(title__icontains=title)
        if qs.exists():
            self.add_error('title', 'This title is taken')
        return data
    

drops/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.forms.models import modelformset_factory
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import DropForm
from .models import Drop



@login_required
def drop_list_view(request, id=None):
    qs = Drop.objects.filter(user=request.user)
    context = {
        "object_list": qs
    }
    return render(request, "drops/list.html", context)

@login_required
def drop_detail_view(request, id=None):
    hx_url = reverse("drops:hx-detail", kwargs={"id": id})
    context = {
        "hx_url": hx_url
    }
    return render(request, "drops/detail.html", context)

@login_required
def drop_delete_view(request, id=None):
    try:
        obj = Drop.objects.get(id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Not Found")
        raise Http404
    if request.method == "POST":
        obj.delete()
        success_url = reverse('drops:list')
        if request.htmx:
            headers = {
                'HX-Redirect': success_url
            }
            return HttpResponse("Success", headers=headers)
        return redirect(success_url)
    context = {
        "object": obj
    }
    return render(request, "drops/single.html", context)

@login_required
def drop_create_view(request):
    form = DropForm(request.POST or None, request.FILES or None)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        if request.htmx:
            headers = {
                "HX-Redirect": obj.get_absolute_url()
            }
            return HttpResponse("Created", headers=headers)
        return redirect(obj.get_absolute_url())
    return render(request, "drops/create-update.html", context=context)

@login_required
def drop_update_view(request, id=None):
    obj = get_object_or_404(Drop, id=id, user=request.user)
    form = DropForm(request.POST or None, request.FILES or None, instance=obj)
    context = {
        "form": form,
        "object": obj,
    }
    if form.is_valid():
        form.save()
        context['message'] = 'Data saved.'
    if request.htmx:
        return render(request, "nftcollections/partials/forms.html", context)
    return render(request, "nftcollections/create-update.html", context)

@login_required
def drop_detail_hx_view(request, id=None):
    try:
        obj = Drop.objects.get(id=id, user=request.user)
    except:
        obj = None
    if obj is  None:
        return HttpResponse("Not found.")
    context = {
        "object": obj
    }
    return render(request, "drops/partials/detail.html", context)

def drop_single_view(request, slug=None):
    drop_obj = None
    if slug is not None:
        try:
            drop_obj = Drop.objects.get(slug=slug)
        except Drop.DoesNotExist:
            raise Http404
        except Drop.MultipleObjectsReturned:
            drop_obj = Drop.objects.filter(slug=slug).first()
        except:
            raise Http404
    context = {
        "object": drop_obj,
    }
    return render(request, "drops/single.html", context=context)

def schedule_view(request, *args, **kwargs):
    drop_queryset = Drop.objects.all()
    total_of_drops = Drop.objects.all().count()

    p = Paginator(drop_queryset, 5)
    page = request.GET.get('page')
    drops = p.get_page(page)
    nums = "a" * drops.paginator.num_pages

    context = {
        "total_of_drops": total_of_drops,
        "drops": drops,
        "nums": nums
    }
    return render(request, "schedule-view.html", context=context)

def drop_search_view(request):
    query = request.GET.get('q')
    qs = Drop.objects.search(query=query)
    context = {
        "object_list": qs
    }
    return render(request, "drops/drop-search.html", context=context)

templates/drops/create-update.html
{% extends "base.html" %}

{% block content %}

<style>
    .nft-form {
        border-bottom: 1px solid black;
    }
    .hidden {
        display: none
    }
    .datepicker-panel > ul[data-view="week"] > li, .datepicker-panel > ul[data-view="week"] > li:hover {
        background: #282828;
    }
    .datepicker-panel > ul > li {
        background: #282525;
    }
    .datepicker-panel > ul > li.picked, .datepicker-panel > ul > li.picked:hover {
        color: #3acc25;
    }
    .datepicker-panel > ul > li:hover {
        background-color: #3b4437;
    }
    .datepicker-panel > ul > li.highlighted {
        background-color: #2f3e2a;
    }
    .datepicker-dropdown {
        border: 1px solid #69c15d;
        box-shadow: 0 3px 6px #79bb62;
    }
    .datepicker-top-left::after, .datepicker-top-right::after {
        border-bottom-color: #3eb93a;
        top: -5px;
    }
</style>

<div style='margin-top:30px;'>
    {% include 'drops/partials/forms.html' %}
</div>

<script>
    $(function () {
      $("#id_release_date").datepicker();
    });
</script>    
{% endblock content %}

templates/drops/detail.html
{% extends "base.html" %}

{% block content %}

<div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class='htmx-indicator'>Loading...</div>
</div>

{% endblock content%}

templates/drops/drop-search.html
{% extends "base.html" %}

{% block content %}
<h1 style="color: #51a82e;">Drop Search (7)</h1>
<ol>
{% for object in object_list %}
    {% if object.title %}
    <li>
        <a href="{{ object.get_absolute_url }}">
            {{ object.title }}
        </a>
    </li>
    {% endif %}
{% endfor %}
</ol>

{% endblock content%}

templates/drops/list.html
{% extends "base.html" %}

{% block content %}
<h1 style="color: #51a82e;">My Drops</h1>
<a href="{% url 'drops:create' %}">Create Drop</a>
<ul>
    {% for x in object_list %}
        <li><a href="{{ x.get_absolute_url }}">{{ x.name }}</a></li>
    {% endfor %}
</ul>

{% endblock content%}

templates/drops/single.html
{% extends "base.html" %}

{% block content %}

<img src="{% if object.image %}{{ object.image.url }}{% endif %}" alt="">
<h1>{{ object.name }}</h1>
{% if object.get_edit_url %}
{% endif %}
<p>{{ object.release_date }}</p>
<p>{{ object.release_time }}</p>
<p>{{ object.description }}</p>
<p>{{ object.genre }}</p>

{% endblock content%}