drops/urls.py
from django.urls import path

from .views import (
    drop_search_view,
    drop_create_view,
    drop_detail_view,
    drop_list_view,
    drop_update_view,
    drop_delete_view,
    drop_detail_hx_view,
    drop_single_view
)

app_name = 'drops'
urlpatterns = [
    path('', drop_list_view, name='list'),
    #path('', drop_search_view, name='search'),
    path('create/', drop_create_view, name='create'),

    path("hx/<int:id>/", drop_detail_hx_view, name='hx-detail'),

    path("<int:id>/delete/", drop_delete_view, name='delete'),
    path("<int:id>/edit/", drop_update_view, name='update'),
    path("<int:id>/", drop_detail_view, name='detail'),

    path('<slug:slug>/', drop_single_view, name='single'),
]

ncollections/urls.py
from django.urls import path

from .views import (
    collection_list_view,
    collection_detail_view,
    collection_create_view,
    collection_update_view,
    collection_delete_view,
    nnft_detail_view,
    nnft_delete_view,
    nnft_create_view,
    nnft_update_view,
    nnft_detail_hx_view,
    ncollection_single_view,
    g_collection_list_view,
    nnft_attribute_delete_view,
    nnft_attribute_update_hx_view
)

app_name = 'ncollections'

urlpatterns = [
    path("", collection_list_view, name="list"),
    path("collection/create/", collection_create_view, name="create"),
    path("<int:id>/delete/", collection_delete_view, name="delete"),
    path("<int:id>/edit/", collection_update_view, name="update"),
    path("<int:id>/", collection_detail_view, name="detail"),

    path("<int:collection_id>/nft/<int:parent_id>/attribute/<int:id>/delete/", nnft_attribute_delete_view, name="attribute-delete"),
    path("hx/nft/<int:parent_id>/attribute/<int:id>", nnft_attribute_update_hx_view, name="hx-attribute-detail"),
    path("hx/nft/<int:parent_id>/attribute/", nnft_attribute_update_hx_view, name="hx-attribute-create"),
    path("<int:parent_id>/nft/create/", nnft_create_view, name="nft-create"),
    path("hx/<int:parent_id>/nft/<int:id>/", nnft_detail_hx_view, name="hx-nft-detail"),
    path("<int:parent_id>/nft/<int:id>/delete/", nnft_delete_view, name="nft-delete"),
    path("<int:parent_id>/nft/<int:id>/edit/", nnft_update_view, name="nft-update"),
    path("<int:parent_id>/nft/<int:id>/", nnft_detail_view, name="nft-detail"),

    path('all/', g_collection_list_view, name='collections'),
    path("<slug:slug>/<int:id>/", ncollection_single_view, name='single-collection'),
]

rargorand/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from drops.views import schedule_view
from nftcollections.views import all_collections_view
from search.views import search_view
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('schedule/', schedule_view, name='schedule'),
    path('allcollections/', all_collections_view, name='collections'),
    path('library/nftcollections/', include('nftcollections.urls')),
    path('library/collections/', include('ncollections.urls')),
    path('calendar/drops/', include('drops.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

ncollections/forms.py
from django import forms
from django.forms.widgets import HiddenInput

from .models import Ncollection, Nnft, Nattribute

class NcollectionForm(forms.ModelForm):
    class Meta:
        model = Ncollection
        fields = ['name', 'image', 'description', 'website', 'social_links']


class NnftForm(forms.ModelForm):
    error_css_class = 'error-field'
    required_css_class = 'required-field'
    #name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "NFT name"}))
    #description = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))
    class Meta:
        model = Nnft
        fields = ['collection', 'name', 'image', 'description', 'link_to_buy', 'attributes']
        widgets = {'collection': forms.HiddenInput()}


class NattributeForm(forms.ModelForm):
    class Meta:
        model = Nattribute
        fields = ['category', 'name']

ncollections/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.forms.models import modelformset_factory
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.core.paginator import Paginator

from .models import Ncollection, Nnft, Nattribute
from .forms import NcollectionForm, NnftForm, NattributeForm

@login_required
def collection_list_view(request):
    qs = Ncollection.objects.filter(user=request.user)
    context = {
        "object_list": qs
    }
    return render(request, "ncollections/list.html", context)

@login_required
def collection_detail_view(request, id=None):
    obj = get_object_or_404(Ncollection, id=id, user=request.user)
    context = {
        "object": obj
    }
    return render(request, "ncollections/detail.html", context)

@login_required
def collection_delete_view(request, id=None):
    obj = get_object_or_404(Ncollection, id=id, user=request.user)
    if request.method == "POST":
        obj.delete()
        success_url = reverse('ncollections:list')
        return redirect(success_url)
    context = {
        "object": obj
    }
    return render(request, "ncollections/delete.html", context)

@login_required
def collection_create_view(request):
    form = NcollectionForm(request.POST or None, request.FILES or None)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        return redirect(obj.get_absolute_url())
    return render(request, "ncollections/create-update.html", context)

@login_required
def collection_update_view(request, id=None):
    obj = get_object_or_404(Ncollection, id=id, user=request.user)
    form = NcollectionForm(request.POST or None, request.FILES or None, instance=obj)
    context = {
        "form": form,
        "object": obj
    }
    if form.is_valid():
        form.save()
        context['message'] = 'Data saved.'
    return render(request, "ncollections/create-update.html", context)

@login_required
def nnft_detail_view(request, parent_id=None, id=None):
    #obj = get_object_or_404(Nnft, collection=parent_id, id=id, user=request.user) # most likely not user, but collection
    hx_url = reverse("ncollections:hx-nft-detail", kwargs={"parent_id": parent_id, "id": id })
    context = {
        "hx_url": hx_url
    }
    return render(request, "ncollections/nft-detail.html", context)

@login_required
def nnft_delete_view(request, parent_id=None, id=None):
    try:
        obj = Nnft.objects.get(collection=parent_id, id=id, user=request.user)
        #obj = get_object_or_404(Nnft, collection=parent_id, id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Not Found")
        raise Http404
    if request.method == "POST":
        obj.delete()
        success_url = reverse('ncollections:detail', kwargs={"id": parent_id})
        if request.htmx:
            headers = {
                'HX-Redirect': success_url
            }
            return HttpResponse("Success", headers=headers)
        return redirect(success_url)
    context = {
        "object": obj
    }
    return render(request, "ncollections/delete-nft.html", context)

@login_required
def nnft_detail_hx_view(request, parent_id=None, id=None):
    if not request.htmx:
        raise Http404
    try:
        obj = Nnft.objects.get(collection=parent_id, id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        return HttpResponse("Not found.")
    context = {
        "object": obj
    }
    return render(request, "ncollections/partials/nft-detail.html", context)

@login_required
def nnft_create_view(request, parent_id=None):
    parent_obj = get_object_or_404(Ncollection, id=parent_id, user=request.user)
    form = NnftForm(request.POST or None, request.FILES or None, initial={'collection': parent_obj.id})
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        return redirect(obj.get_hx_url())
    return render(request, "ncollections/nft-create-update.html", context)


@login_required
def nnft_update_view(request, parent_id=None, id=None):
    obj = get_object_or_404(Nnft, collection=parent_id, id=id, user=request.user)
    form = NnftForm(request.POST or None, request.FILES or None, instance=obj)
    new_attribute_url = reverse("ncollections:hx-attribute-create", kwargs={"parent_id": obj.id})
    context = {
        "form": form,
        "object": obj,
        "new_attribute_url": new_attribute_url 
    }
    if form.is_valid():
        form.save()
        context['message'] = 'Data saved.'
    if request.htmx:
        return render(request, "ncollections/partials/forms.html", context)
    return render(request, "ncollections/nft-create-update.html", context)  


@login_required
def nnft_attribute_delete_view(request, collection_id=None, parent_id=None, id=None):
    try:
        obj = Nattribute.objects.get(nft__id=parent_id, id=id, nft__user=request.user)
        #obj = get_object_or_404(Nnft, collection=parent_id, id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Not Found")
        raise Http404
    if request.method == "POST":
        obj.delete()
        kwargs = {
            "parent_id": collection_id,
            "id": parent_id   
        }
        success_url = reverse('ncollections:nft-detail', kwargs=kwargs)
        if request.htmx:
            headers = {
                'HX-Redirect': success_url
            }
            return HttpResponse("Success", headers=headers)
        return redirect(success_url)
    context = {
        "object": obj
    }
    return render(request, "ncollections/delete-nft.html", context)


@login_required
def nnft_attribute_update_hx_view(request, parent_id=None, id=None):
    if not request.htmx:
       raise Http404
    try:
        parent_obj = Nnft.objects.get(id=parent_id, user=request.user)
    except:
        parent_obj = None
    if parent_obj is None:
        return HttpResponse("Not found.")
    instance = None
    if id is not None:  
        try:
            instance = Nattribute.objects.get(nft=parent_obj, id=id)
        except:
            instance = None
    form = NattributeForm(request.POST or None, instance=instance)
    url = reverse("ncollections:hx-attribute-create", kwargs={"parent_id": parent_obj.id})
    if instance:
        url = instance.get_hx_edit_url()
    context = {
        "url": url,
        "form": form,
        "object": instance
    }
    if form.is_valid():
        new_obj = form.save(commit=False)
        if instance is None:
            new_obj.nft = parent_obj
        new_obj.save()
        context['object'] = new_obj
        return render(request, "ncollections/partials/attribute-inline.html", context)
    return render(request, "ncollections/partials/attribute-form.html", context)

def ncollection_single_view(request, slug=None, id=None):
    collection_obj = None
    list_of_nfts = Nnft.objects.filter(collection=id) #filter(collection__name=slug).all()
    total_of_nfts = len(list_of_nfts)
   
    if slug is not None:
        try:
            collection_obj = Ncollection.objects.get(slug=slug)
        except Ncollection.DoesNotExist:
            raise Http404
        except Ncollection.MultipleObjectsReturned:
            collection_obj = Ncollection.objects.filter(slug=slug).first()
        except:
            raise Http404
    
    p = Paginator(list_of_nfts, 24)
    page = request.GET.get('page')
    nfts = p.get_page(page)
    nums = "a" * nfts.paginator.num_pages

    context = {
        "object": collection_obj,
        "total_of_nfts": total_of_nfts,
        "nfts": nfts,
        "nums": nums
    }
    return render(request, "ncollections/single.html", context=context)

def g_collection_list_view(request):
    collection_queryset = Ncollection.objects.all()
    context = {
        "object_list": collection_queryset,
    }
    return render(request, "ncollections/collection-list.html", context=context)

templates/ncollections/collection-list.html
{% extends "base.html" %}

{% block content %}

<div class="page-title">
    <h1>All Collections</h1>
</div>

<div class="row">
    <div class="all-collections-table">
        <table>
            <colgroup>
                <col span="1" class="number-col">
                <col span="1" class="collection-col">
                <col span="1" class="vol-col">
                <col span="1" class="weeklyvol-col">
                <col span="1" class="added-col">
            </colgroup>
            <tr>
                <th>#</th>
                <th>Collection</th>
                <th>Volume</th>
                <th>Volume (7d)</th>
                <th>Added</th>
            </tr>
            {% for x in object_list %}
            <tr>
                <td></td>
                {% if not request.user.is_authenticated or user.id != x.user.id %}
                <td><img src="{% if x.image %}{{ x.image.url }}{% endif %}" alt=""><a href="{{ x.get_single_collection_url }}">{{ x.name }}</a></td>
                {% else %}
                <td><img src="{% if x.image %}{{ x.image.url }}{% endif %}" alt=""><a href="{{ x.get_absolute_url }}">{{ x.name }}</a></td>
                {% endif %}
                <td>{{ x.volume }} ALGO</td>
                <td>{{ x.weeklyvolume }} ALGO</td>
                <td>{{ x.timestamp }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<script>
    var table = document.getElementsByTagName('table')[0],
    rows = table.getElementsByTagName('tr'),
    text = 'textContent' in document ? 'textContent' : 'innerText';

    for (var i = 0, len = rows.length; i < len; i++) {
        var k = i + 1;
        rows[k].children[0][text] = k;
    }
</script>

{% endblock content%}

templates/ncollections/create-update.html
{% extends "base.html" %}

{% block content %}

{% if message %}
<p>{{ message }}</p>
{% endif %}

<div style="margin-top:30px">
    <form action="." method="POST" enctype="multipart/form-data" hx-encoding="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button style="margin-top: 10px;" type="submit">Save</button>
    </form>
</div>

{% endblock content%}

templates/ncollections/delete-nft.html
{% extends "base.html" %}


{% block content %}

{% if object %}
<form method='POST' action='.'>
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.name }}</p>
    <button type='submit'>Yes, delete.</button>
</form>
{% endif %}

{% endblock content %}

templates/ncollections/delete.html
{% extends "base.html" %}


{% block content %}

{% if object %}
<form method='POST' action='.'>
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.name }}</p>
    <button type='submit'>Yes, delete.</button>
</form>
{% endif %}

{% endblock content %}

templates/ncollections/detail.html
{% extends "base.html" %}

{% block content %}

<img src="{% if object.image %}{{ object.image.url }}{% endif %}" alt="">
<h1>{{ object.name }} </h1> 
{% if object.get_edit_url %}
<small>
    <a href="{{ object.get_edit_url }}">Edit</a>
    <a href="{{ object.get_delete_url }}">Delete</a>
    <a href="{{ object.get_nft_create_url }}">Add NFT</a>
</small>
{% endif %}
<p>{{ object.volume }}</p>
<p>{{ object.weekly_volume }}</p>
<p>{{ object.timestamp }}</p>
<p>{{ object.description }}</p>
<p>{{ object.website }}</p>
<p>{{ object.social_links }}</p>


<h3>NFTs</h3>
{% for nft in object.get_nft_children %}
<img src="{% if nft.image %}{{nft.image.url }}{% endif %}" alt="">
<a href="{{ nft.get_detail_url }}"><h2>{{ nft.name }}</h2></a>
<p>{{ nft.description }}</p>
{% endfor %}

{% endblock content%}

templates/ncollections/list.html
{% extends "base.html" %}

{% block content %}
<h1>My NFT Collections</h1>
<a href="{% url 'ncollections:create' %}">Create Collection</a>
<ul>
    {% for x in object_list %}
        <li><a href="{{ x.get_absolute_url }}">{{ x.name }}</a></li>
    {% endfor %}
</ul>

{% endblock content%}

templates/ncollections/nft-create-update.html
{% extends "base.html" %}

{% block content %}

{% if message %}
<p>{{ message }}</p>
{% endif %}

<style>
    .hidden {
        display: none;
    }
</style>

<div style='margin-top:30px;'>
    {% include 'ncollections/partials/forms.html' %}

    {% if object %}
    <h3>Attributes</h3>
    {% endif %}

    {% for attr in object.get_attribute_children %}
    <div class="">
        {% include 'ncollections/partials/attribute-inline.html' with object=attr %}
    </div>
    {% endfor %}

    {% if new_attribute_url %}
    <div id="attribute-create">

    </div>
    <button hx-get="{{ new_attribute_url }}" hx-trigger='click' hx-target="#attribute-create" hx-swap='beforeend' type='button'>Add Attribute</button>
    {% endif %}
</div>

<script>
    
    
    const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
    document.addEventListener('click', (event)=>{
        if (event.target.id == 'add-more') {
            add_new_form(event)
        }
    })

    function add_new_form(event) {
        if (event) {
            event.preventDefault()
        }
        const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
        const currentIngredientForms = document.getElementsByClassName('attribute-form')
        const currentFormCount = currentIngredientForms.length // + 1
        const formCopyTarget = document.getElementById('attributes-form-list')
        const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
        copyEmptyFormEl.setAttribute('class', 'attributes-form')
        copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
        const regex = new RegExp('__prefix__', 'g')
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
        totalNewForms.setAttribute('value', currentFormCount + 1)
        // now add new empty form element to our html form
        formCopyTarget.append(copyEmptyFormEl)
    }
    


</script>



{% endblock content %}

templates/ncollections/nft-detail.html
{% extends "base.html" %}

{% block content %}

<div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class='htmx-indicator'>Loading...</div>
</div>


{% endblock content%}

templates/ncollections/single.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="single-collection-top">
        <img src="{% if object.image %}{{ object.image.url }}{% endif %}" alt="Collection Logo">
        <h1>{{ object.name }}</h1>
    </div>
</div>

<div class="row">
    <div class="single-collection-numbers">
        <p class="volume"> <span class="single-collection-numbers-label">Volume:</span> {{ object.volume }} ALGO</p>
        <p class="weekly-volume"> <span class="single-collection-numbers-label">Weekly Volume:</span> {{ object.weekly_volume }} ALGO</p>
        <p class="timestamp"><span class="timestamp-value"><span class="single-collection-numbers-label">Added:</span> {{ object.timestamp }}</span></p>
    </div>
</div>

<div class="row">
    <div class="single-collection-description">
        <h3>Description:</h3>
        <p>{{ object.description }}</p>
    </div>      
</div>

<div class="row">
    <div class="single-collection-website">
        <span class="single-collection-numbers-label">Website:</span> <a href="https://{{ object.website }}">{{ object.website }}</a></p>
    </div>
</div>

<div class="row">
    <div class="single-collection-social-links">
        <p>{{ object.social_links }}</p>
    </div>
</div>

<div class="row nft-gallery-content">
    <div class="col-2">
        <div class="nft-filters">
            <h2>Filters:</h2>
        </div>
    </div>
    <div class="col-10">
        <div class="total-of-nfts">
            <p>Total Nfts: {{ total_of_nfts }}</p>
        </div>
        <div class="grid-container-nft-gallery">
            {% for nft in nfts %}
            <div class="grid-nft" style="background-image: url({% if nft.image %}{{ nft.image.url }}{% endif %});">
                <div class="nft-content">
                    <a href="#">{{ nft.name }}</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
              <li class="page-item">
                {% if nfts.has_previous %}
                <a class="page-link " href="?page={{ nfts.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
                {% endif %}
              </li>
              {% for i in nums %}
              <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
              {% endfor %}
              <li class="page-item">
                {% if nfts.has_next %}
                <a class="page-link " href="?page={{ nfts.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
              </li>
            </ul>
          </nav>
    </div>
</div>

{% endblock content%}