drops/urls.py
from django.urls import path

from .views import (
    drop_search_view,
    drop_create_view,
    drop_detail_view,
    drop_list_view,
    drop_update_view,
    drop_delete_view,
    drop_detail_hx_view,
    drop_single_view
)

app_name = 'drops'
urlpatterns = [
    path('', drop_list_view, name='list'),
    #path('', drop_search_view, name='search'),
    path('create/', drop_create_view, name='create'),

    path("hx/<int:id>/", drop_detail_hx_view, name='hx-detail'),

    path("<int:id>/delete/", drop_delete_view, name='delete'),
    path("<int:id>/edit/", drop_update_view, name='update'),
    path("<int:id>/", drop_detail_view, name='detail'),

    path('<slug:slug>/', drop_single_view, name='single'),
]

ncollections/urls.py
from django.urls import path

from .views import (
    collection_list_view,
    collection_detail_view,
    collection_create_view,
    collection_update_view,
    collection_delete_view,
    nnft_detail_view,
    nnft_delete_view,
    nnft_create_view,
    nnft_update_view,
    nnft_detail_hx_view,
    ncollection_single_view,
    g_collection_list_view,
    nnft_attribute_delete_view,
    nnft_attribute_update_hx_view
)

app_name = 'ncollections'

urlpatterns = [
    path("", collection_list_view, name="list"),
    path("collection/create/", collection_create_view, name="create"),
    path("<int:id>/delete/", collection_delete_view, name="delete"),
    path("<int:id>/edit/", collection_update_view, name="update"),
    path("<int:id>/", collection_detail_view, name="detail"),

    path("<int:collection_id>/nft/<int:parent_id>/attribute/<int:id>/delete/", nnft_attribute_delete_view, name="attribute-delete"),
    path("hx/nft/<int:parent_id>/attribute/<int:id>", nnft_attribute_update_hx_view, name="hx-attribute-detail"),
    path("hx/nft/<int:parent_id>/attribute/", nnft_attribute_update_hx_view, name="hx-attribute-create"),
    path("<int:parent_id>/nft/create/", nnft_create_view, name="nft-create"),
    path("hx/<int:parent_id>/nft/<int:id>/", nnft_detail_hx_view, name="hx-nft-detail"),
    path("<int:parent_id>/nft/<int:id>/delete/", nnft_delete_view, name="nft-delete"),
    path("<int:parent_id>/nft/<int:id>/edit/", nnft_update_view, name="nft-update"),
    path("<int:parent_id>/nft/<int:id>/", nnft_detail_view, name="nft-detail"),

    path('all/', g_collection_list_view, name='collections'),
    path("<slug:slug>/<int:id>/", ncollection_single_view, name='single-collection'),
]

rargorand/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from drops.views import schedule_view
from nftcollections.views import all_collections_view
from search.views import search_view
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('schedule/', schedule_view, name='schedule'),
    path('allcollections/', all_collections_view, name='collections'),
    path('library/nftcollections/', include('nftcollections.urls')),
    path('library/collections/', include('ncollections.urls')),
    path('calendar/drops/', include('drops.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/ico.svg' %}">
    <title>Rargorand</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
    <link rel="stylesheet" href='{% static "nftcollections/nftcollections-htmx.css" %}'>
    <link rel="stylesheet" href='{% static "home.css" %}'>
    <link rel="stylesheet" href='{% static "allcollections.css" %}'>
    <link rel="stylesheet" href='{% static "schedule.css" %}'>
    <link rel="stylesheet" href='{% static "single-collection.css" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;300;400;500&display=swap" rel="stylesheet"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet"> 

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'base/navbar.html' %}
    <main class="main-content">
        <div class="container">
            {% block content %}
            {% endblock content%}
        </div>
    </main>
    {% include 'base/footer.html' %}
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener("htmx:configRequest", (event)=>{
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
        })
    </script>
    
</body>
</html>

templates/collections-view.html
{% extends "base.html" %}

{% block content %}

<div class="page-title">
    <h1>All Collections</h1>
</div>

<div class="row">
    <div class="all-collections-table">
        <table>
            <colgroup>
                <col span="1" class="number-col">
                <col span="1" class="collection-col">
                <col span="1" class="vol-col">
                <col span="1" class="weeklyvol-col">
                <col span="1" class="added-col">
            </colgroup>
            <tr>
                <th>#</th>
                <th>Collection</th>
                <th>Volume</th>
                <th>Volume (7d)</th>
                <th>Added</th>
            </tr>
            {% for x in object_list %}
            <tr>
                <td></td>
                {% if not request.user.is_authenticated or user.id != x.user.id %}
                <td><img src="{% if x.image %}{{ x.image.url }}{% endif %}" alt=""><a href="{{ x.get_single_collection_url }}">{{ x.name }}</a></td>
                {% else %}
                <td><img src="{% if x.image %}{{ x.image.url }}{% endif %}" alt=""><a href="{{ x.get_absolute_url }}">{{ x.name }}</a></td>
                {% endif %}
                <td>{{ x.volume }} ALGO</td>
                <td>{{ x.weeklyvolume }} ALGO</td>
                <td>{{ x.timestamp }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<script>
    let table = document.getElementsByTagName('table')[0]
    let rows = table.getElementsByTagName('tr')
    let text = 'textContent' in document ? 'textContent' : 'innerText';

    for (let i = 0, len = rows.length; i < len; i++) {
        let k = i + 1;
        rows[k].children[0][text] = k;
    }
</script>

{% endblock content%}

templates/home-view.html
{% extends "base.html" %}

{% block content %}

<style>
    
</style>

<section class="section-style new-collections-s">
    <div class="container">
        <div class="row">
            <div class="page-title">
                <h1>Newest Collections</h1>
            </div>
            <div class="grid-container-collection">
                <div class="grid-item-3 featured-collection">
                    {% for x in featured_collection %}
                        <div class="featured-collection-card">
                            <div class="featured-collection-flag" >
                                <p>Featured Collection</p>
                            </div>
                            {% if x.image %}
                            <img src="{{ x.image.url }}" alt="">
                            {% endif %}
                            <div class="featured-collection-name">{{ x.name }}</div>
                            <div class="featured-collection-description">{{ x.description }}</div>
                            <div class="featured-collection-card-bottom">
                                <div class="featured-collection-volume">Volume: {{ x.volume }} ALGO</div>
                                <div class="featured-collection-added">Added: {{ x.timestamp }}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% for x in new_collections %}
                <div class="grid-item">
                    <div class="collection-card">
                        {% if x.image %}
                        <img src="{{ x.image.url }}" alt="">
                        {% endif %}
                        <div class="collection-name">{{ x.name }}</div>
                        <div class="collection-description">{{ x.description }}</div>
                        <div class="collection-card-bottom">
                            <div class="collection-volume">Volume:<br>{{ x.volume }} ALGO</div>
                            <div class="collection-added">Added: {{ x.timestamp }}</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="link-to-all">
                <a href="{% url 'ncollections:collections' %}">Explore All Collections -></a>
            </div>
        </div>
    </div>
</section>

<section class="section-style upcoming-drops-s">
    <div class="container">
        <div class="row">
            <div class="page-title">
                <h1>Upcoming Drops</h1>
            </div>
            <div class="grid-container-drop">
                {% for x in featured_drop %}
                {% if x.image %}
                <div class="featured-drop" style="background-image: url({{ x.image.url }});">
                    <div class="featured-drop-flag" >
                        <p>Featured Drop</p>
                    </div>
                    <div class="upcoming-drop-card-content">
                        <div class="drop-name">{{ x.name }}</div>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                </div> 
                {% endif %}
                {% endfor %}

                {% for x in most_anticipated %}
                {% if x.image %}
                <div class="anticipated" style="background-image: url({{ x.image.url }});">
                    <div class="featured-drop-flag" >
                        <p>Most Anticipated</p>
                    </div>
                    <div class="upcoming-drop-card-content">
                        <div class="drop-name">{{ x.name }}</div>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                </div> 
                {% endif %}
                {% endfor %}

                {% for x in future_favourite %}
                {% if x.image %}
                <div class="favourite" style="background-image: url({{ x.image.url }});">
                    <div class="featured-drop-flag" >
                        <p>Future Favourite</p>
                    </div>
                    <div class="upcoming-drop-card-content">
                        <div class="drop-name">{{ x.name }}</div>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                </div> 
                {% endif %}
                {% endfor %}
                
                
                {% for x in upcomming_drops %}
                <div class="upcoming-drop">
                    {% if x.image %}
                    <div class="upcoming-drop-wrap" style="background-image: url({{ x.image.url }});">
                    {% endif %}
                    <div class="upcoming-drop-card-content">
                        <div class="drop-name">{{ x.name }}</div>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="link-to-all">
                <a href="{% url 'schedule' %}">Open Schedule -></a>
            </div>
        </div>
    </div>
</section>
<!--
<section class="section-style top-collections">
    <div class="row">
        <div class="page-title">
            <h1>Top Collection</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-4">By 7 Day Volume</div>
        <div class="col-4">By Total Volume</div>
        <div class="col-4">By Owner Count</div>
    </div>
</section>
-->
{% endblock content%}

templates/image-form.html
{% extends "base.html" %}


{% block content %}

<form action='.' method="POST" enctype="multipart/form-data" hx-post="{{ request.path }}" hx-encoding="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button style='margin-top:10px;' type='submit' >Upload Image</button>
</form>

{% endblock content %}

templates/schedule-view.html
{% extends "base.html" %}

{% block content %}


<div class="page-title">
    <h1>Schedule</h1>
</div>
<div class="row">
    <div class="total-of-drops">
        <p>{{ total_of_drops }} Total Upcoming</p>
    </div>
</div>

<div class="row">
    <div class="grid-container-schedule">
        {% for x in drops %}
            {% if x.title %}
                {% if not request.user.is_authenticated or user.id != x.user.id %}
                <div class="grid-drop" style="background-image: url({% if x.image %}{{ x.image.url }}{% endif %});">
                    <div class="drop-content">
                        <a href="{{ x.get_single_drop_url }}">{{ x.title }}</a>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                </div>
                {% else %}
                <div class="grid-drop" style="background-image: url({% if x.image %}{{ x.image.url }}{% endif %});">
                    <div class="drop-content">
                        <a href="{{ x.get_single_drop_url }}">{{ x.title }}</a>
                        <div class="drop-date-time">{{ x.release_date }} - {{ x.release_time }}</div>
                    </div>
                </div>
                {% endif %}
                
            {% endif %}
        {% endfor %}
    </div>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      <li class="page-item">
        {% if drops.has_previous %}
        <a class="page-link " href="?page={{ drops.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        {% endif %}
      </li>
      {% for i in nums %}
      <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
      {% endfor %}
      <li class="page-item">
        {% if drops.has_next %}
        <a class="page-link " href="?page={{ drops.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </nav>

{% endblock content%}